USE master;
-- Create database
GO
CREATE DATABASE %COMMENTDB% COLLATE SQL_Latin1_General_CP1_CI_AS;
GO
-- Minimizing deadlock potential
ALTER DATABASE %COMMENTDB% SET READ_COMMITTED_SNAPSHOT ON;
-- Create logins
GO
CREATE LOGIN "%COMMENTUSER%" WITH PASSWORD = '%COMMENTUSERPASSWORD%';
GO
CREATE LOGIN "%COMMENTADMINUSER%" WITH PASSWORD = '%COMMENTADMINUSERPASSWORD%';
GO
USE %COMMENTDB%;
-- Create users on correct DATABASE (after use) and with correct schema
GO
CREATE USER "%COMMENTUSER%" FOR LOGIN "%COMMENTUSER%" WITH DEFAULT_SCHEMA = %COMMENTDB%;
GO
CREATE USER "%COMMENTADMINUSER%" FOR LOGIN "%COMMENTADMINUSER%" WITH DEFAULT_SCHEMA = %COMMENTDB%;
-- Create schema
GO
CREATE SCHEMA %COMMENTDB% AUTHORIZATION "%COMMENTADMINUSER%";
-- Grant access
GO
GRANT CREATE TABLE, ALTER, SELECT, INSERT, UPDATE, DELETE ON DATABASE::%COMMENTDB% TO "%COMMENTADMINUSER%";
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::%COMMENTDB% TO "%COMMENTUSER%";
GO