USE master;
GO
-- Create database
CREATE DATABASE %DASHBOARDDB% COLLATE SQL_Latin1_General_CP1_CI_AS;
GO
-- Minimizing deadlock potential
ALTER DATABASE %DASHBOARDDB% SET READ_COMMITTED_SNAPSHOT ON;
GO
-- Create logins
CREATE LOGIN "%DASHBOARDUSER%" WITH PASSWORD = '%DASHBOARDUSERPASSWORD%';
GO
CREATE LOGIN "%DASHBOARDADMINUSER%" WITH PASSWORD = 'DASHBOARDADMINUSERPASSWORD';
GO
USE %DASHBOARDDB%;
GO
-- Create users on correct DATABASE (after use) and with correct schema
--(schema can be created after it will not CREATE USER "%DASHBOARDUSER%" FOR LOGIN "%DASHBOARDUSER%" WITH DEFAULT_SCHEMA = passport;
CREATE USER "%DASHBOARDUSER%" FOR LOGIN "%DASHBOARDUSER%" WITH DEFAULT_SCHEMA = %DASHBOARDDB%;
GO
CREATE USER "%DASHBOARDADMINUSER%" FOR LOGIN "%DASHBOARDADMINUSER%" WITH DEFAULT_SCHEMA = %DASHBOARDDB%;
GO
-- Create schema
CREATE SCHEMA %DASHBOARDDB% AUTHORIZATION "%DASHBOARDADMINUSER%";
GO
-- Grant access
GRANT CREATE TABLE, ALTER, SELECT, INSERT, UPDATE, DELETE ON DATABASE::%DASHBOARDDB% TO "%DASHBOARDADMINUSER%";
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON SCHEMA::%DASHBOARDDB% TO "%DASHBOARDUSER%";
GO


