USE master;
-- Create database
GO
CREATE DATABASE %SPACEDB% COLLATE SQL_Latin1_General_CP1_CS_AS;
GO
-- Minimizing deadlock potential
ALTER DATABASE %SPACEDB% SET READ_COMMITTED_SNAPSHOT ON;
-- Create logins
GO
CREATE LOGIN %SPACEUSER% WITH PASSWORD = '%SPACEPASSWORD%';
GO
USE %SPACEDB%;
-- Create user on correct DATABASE (after use) and with correct schema
GO
CREATE USER %SPACEUSER% FOR LOGIN %SPACEUSER% WITH DEFAULT_SCHEMA = %SPACEDB%;
-- Create schema
GO
CREATE SCHEMA %SPACEDB% AUTHORIZATION %SPACEUSER%;
GO
-- Grant access
GRANT CREATE TABLE, ALTER, SELECT, INSERT, UPDATE, DELETE ON DATABASE::%SPACEDB% TO %SPACEUSER%;
GO
