create user M1 identified by M1;
grant connect, resource, create view to M1;
grant UNLIMITED TABLESPACE to "M1";
CREATE SMALLFILE TABLESPACE "M1" LOGGING DATAFILE 'D:\Oracle\oradata\V6R2017X\M1.dbf' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
ALTER USER M1 default tablespace M1;

CREATE SMALLFILE TABLESPACE "I1_DATA" LOGGING DATAFILE 'D:\Oracle\oradata\V6R2017X\I1_DATA.dbf' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
CREATE SMALLFILE TABLESPACE "I1_INDEX" LOGGING DATAFILE 'D:\Oracle\oradata\V6R2017X\I1_INDEX.dbf' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
CREATE SMALLFILE TABLESPACE "M1_DATA" LOGGING DATAFILE 'D:\Oracle\oradata\V6R2017X\M1_DATA.dbf' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
CREATE SMALLFILE TABLESPACE "M1_INDEX" LOGGING DATAFILE 'D:\Oracle\oradata\V6R2017X\M1_INDEX.dbf' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;

ALTER USER M1 QUOTA UNLIMITED ON I1_DATA;
ALTER USER M1 QUOTA UNLIMITED ON I1_INDEX;
ALTER USER M1 QUOTA UNLIMITED ON M1_DATA;
ALTER USER M1 QUOTA UNLIMITED ON M1_INDEX;
ALTER USER M1 QUOTA UNLIMITED ON M1;

